---
apiVersion: tekton.dev/v1alpha1
kind: Task
metadata:
  name: unit-tests-task
spec:
  inputs:
    params:
      - name: pipelineRunId
        description: pipelineRunId unique id
      - name: task-pvc
        description: the output pvc - this is where the cloned repository will be stored
      - name: context
        description: the context of the unit tests
      - name: pipeline-debug
        description: Pipeline debug mode
        default: "0"
  stepTemplate:
    env:
      - name: PIPELINE_DEBUG
        value: $(inputs.params.pipeline-debug)
  steps:
    - name: unit-tests
      image: ibmcom/pipeline-base-image:latest
      env:
        - name: PIPELINE_RUN_ID
          value: $(inputs.params.pipelineRunId)
        - name: CONTEXT
          value: $(inputs.params.context)
      command: ["/bin/bash", "-c"]
      args:
        - |
          . /root/.nvm/nvm.sh

          if [ $PIPELINE_DEBUG == 1 ]; then
            env
            cat /cd-config/toolchain.json
            trap env EXIT
            set -x
          fi

          function set-status() {
            local repo=$1
            local state=$2
            local context=$3
            local description=$4
            local body="{\"state\": \"$state\", \"target_url\": \"$TOOLCHAIN_URL\",\
            \"description\": \"$description\", \"context\": \"$context\"}"

            curl "https://github.ibm.com/api/v3/repos/$repo/statuses/$GIT_COMMIT" \
              -H "Authorization: Bearer $GHE_TOKEN" \
              -H "Content-Type: application/json" \
              -d "$body"
          }

          source /artifacts/build.properties

          GH_ORG=$(jq -r '.services[] | select(.toolchain_binding.name=="app-repo") |
          .parameters.owner_id' /cd-config/toolchain.json)
          PIPELINE_ID=$(jq -r '.services[] | select(.service_id=="pipeline") | .instance_id' /cd-config/toolchain.json)
          PIPELINE_REGION=$(jq -r '.services[] | select(.service_id=="pipeline") |
          .region_id' /cd-config/toolchain.json)
          JOB_URL="https://cloud.ibm.com/devops/pipelines/tekton/$PIPELINE_ID/runs/$PIPELINE_RUN_ID?env_id=$PIPELINE_REGION"
          TOOLCHAIN_ID=$(jq -r '.toolchain_guid' /cd-config/toolchain.json)
          TOOLCHAIN_REGION=$(jq -r '.region_id' /cd-config/toolchain.json)
          TOOLCHAIN_URL="https://cloud.ibm.com/devops/toolchains/$TOOLCHAIN_ID?env_id=$TOOLCHAIN_REGION"

          set-status $GH_ORG/$REPO pending $CONTEXT

          cd /artifacts/$APP_DIRECTORY
          npm ci

          if npm test; then
            set-status $GH_ORG/$REPO success $CONTEXT
          else
            set-status $GH_ORG/$REPO failure $CONTEXT
          fi
      volumeMounts:
        - mountPath: /artifacts
          name: task-volume
        - mountPath: /cd-config
          name: cd-config-volume
  volumes:
    - name: task-volume
      persistentVolumeClaim:
        claimName: $(inputs.params.task-pvc)
    - name: cd-config-volume
      configMap:
        name: toolchain
        items:
          - key: toolchain.json
            path: toolchain.json
