---
apiVersion: tekton.dev/v1alpha1
kind: Task
metadata:
  name: merge-cr-inventory-branch
spec:
  inputs:
    params:
      - name: task-pvc
        description: the output pvc - this is where the cloned repository will be store
      - name: pipeline-debug
        description: Pipeline debug mode
        default: "0"
  stepTemplate:
    env:
      - name: PIPELINE_DEBUG
        value: $(inputs.params.pipeline-debug)
  steps:
    - name: merge
      image: ibmcom/pipeline-base-image
      command: ["/bin/bash", "-c"]
      args:
        - |
          #!/bin/bash
          source /artifacts/build.properties

          git clone https://${GIT_AUTH_USER}:${GHE_TOKEN}@github.ibm.com/cocoa/inventory-script.git
          cd inventory-script
          source inventory.sh

          if [ $PIPELINE_DEBUG == 1 ]; then
            env
            cat /cd-config/toolchain.json
            trap env EXIT
            set -x
          fi

          cd ..
          cd /artifacts/$INVENTORY_FOLDER

          git config --global user.email "tekton@pipeline.com"
          git config --global user.name "Tekton"

          inventory cr apply $CHANGE_REQUEST_ID

      volumeMounts:
        - mountPath: /artifacts
          name: task-volume
        - mountPath: /cd-config
          name: cd-config-volume
  volumes:
    - name: task-volume
      persistentVolumeClaim:
        claimName: $(inputs.params.task-pvc)
    - name: cd-config-volume
      configMap:
        name: toolchain
        items:
          - key: toolchain.json
            path: toolchain.json
