---
apiVersion: tekton.dev/v1alpha1
kind: Task
metadata:
  name: gitsecure-vulnerability-remediation-task
spec:
  inputs:
    params:
      - name: task-pvc
        description: the output pvc
      - name: repository
        description: the git repo
      - name: revision
        description: the revision
        default: master
      - name: api-key
        description: the ibmcloud api key
      - name: pipeline-run-id
        description: pipelinerun id
      - name: pr-url
        description: pull request url
      - name: commit-id
        description: git commit id
  steps:
    - name: remediation
      image: wcp-compliance-automation-team-docker-local.artifactory.swg-devops.com/gitsecure/remediation-task:1.0.0
      imagePullPolicy: Always
      command:
        - /go/src/github.ibm.com/rig-recommend/rig-recommend
      args:
        - "-giturl"
        - $(inputs.params.repository)
        - "-gitbranch"
        - $(inputs.params.revision)
        - "-repodir"
        - "/workspace"
        - "-rigserviceapi"
        - "http://169.47.180.157:30850"
        - "-pr"
        - $(inputs.params.pr-url)
        - "-apikey"
        - $(inputs.params.api-key)
        - "-runid"
        - $(inputs.params.pipeline-run-id)
        - "-region"
        - "us-south"
        - "-commitid"
        - $(inputs.params.commit-id)
      volumeMounts:
        - mountPath: /artifacts
          name: task-volume
  volumes:
    - name: task-volume
      persistentVolumeClaim:
        claimName: $(inputs.params.task-pvc)
